---
resource_types:
  - name: google-cloud-storage
    type: docker-image
    source:
      repository: frodenas/gcs-resource

resources:
  # - name: 1m
  #   type: time
  #   source: {interval: 1m}

  - name: buildpacks-repo
    type: google-cloud-storage
    source:
      bucket: {{repo}}
      regexp: java-buildpack-offline-v(.*).zip
      json_key: {{gcs-key}}

  - name: app-repo
    type: google-cloud-storage
    source:
      bucket: {{gcs-bucket-releases}}
      regexp: pcfdemoapp-(.*).jar
      json_key: {{gcs-key}}

  - name: version-repo
    type: google-cloud-storage
    source:
      bucket: {{ver-bucket}}
      regexp: java-bp-v(.*).prop
      json_key: {{gcs-key}}
      
  - name: manifest-repo
    type: git
    source:
      uri: {{github-uri}}
      branch: {{github-branch}}

  - name: cf-staging
    type: cf
    source:
      api: {{cf-api}}
      username: {{cf-username}}
      password: {{cf-password}}
      organization: {{cf-org}}
      space: {{cf-space-staging}}
      skip_cert_check: true

  - name: cf-production
    type: cf
    source:
      api: {{cf-api}}
      username: {{cf-username}}
      password: {{cf-password}}
      organization: {{cf-org}}
      space: {{cf-space-prod}}
      skip_cert_check: true

jobs: 
  - name: sync-it-with-pivnet
    plan:
      # - get: 1m
      #   trigger: true
      - get: buildpacks-repo
        trigger: true
      - get: app-repo
      - get: manifest-repo
      - task: upload-to-PCF
        config:
            platform: linux
            image_resource:
              type: docker-image
              source:
                repository: governmentpaas/cf-cli
            inputs:
              - name: app-repo
              - name: buildpacks-repo
              - name: manifest-repo
            outputs:
              - name: buildpack
              - name: app
              - name: manifest
            params: 
              api: {{cf-api}}
              user: {{cf-admin}}
              pass: {{cf-admin-pass}}
              org: {{cf-org}}
              space: {{cf-space-prod}}
            run:
              path: sh
              args:
              - -c
              - |
                ls -ltr buildpacks-repo
                ls -ltr app-repo
                ls -ltr manifest-repo
                tempname=`basename buildpacks-repo/java-*.zip`
                echo ${tempname%.zip} 
                bpname=`echo ${tempname%.zip}`
                echo $bpname
                echo $bpname | sed -e 's/[^0-9]//g'
                version=`echo $bpname | sed -e 's/[^0-9]//g'` 

                app=`basename app-repo/*.jar` 

                bpname_f=java_buildpack_v$version

                cf login -a $api -u $user -p $pass -o $org -s $space --skip-ssl-validation
                cf create-buildpack $bpname_f buildpacks-repo/java-*.zip 1 --enable
                cf buildpacks

                str1="buildpack:"
                str2="path:"

                echo $bpname_f > manifest/java-bp-v$version.prop

                echo $'  '$str1$' '$bpname_f >> manifest-repo/manifest-staging.yml
                echo $'  '$str2$' '$app >> manifest-repo/manifest-staging.yml
                cat manifest-repo/manifest-staging.yml

                cp app-repo/$app manifest/$app
                cp manifest-repo/manifest-staging.yml manifest/manifest-staging.yml

                cat manifest/manifest-staging.yml
                echo $bpname_f>latest_version

                ls -ltr manifest
      - put: cf-staging
        params:
          manifest: manifest/manifest-staging.yml
      - put: version-repo
        params:
          file: manifest/java-bp-*.prop

  - name: test
    serial: true
    plan:
      - get: app-repo
        passed: [ sync-it-with-pivnet ]
      - get: manifest-repo
        passed: [ sync-it-with-pivnet ]
      - get: version-repo
        trigger: true
        passed: [ sync-it-with-pivnet ]
      - task: smoke-test
        config:
            inputs:
              - name: app-repo
              - name: manifest-repo
              - name: version-repo
            outputs: 
              - name: finaldir
            platform: linux
            image_resource:
              type: docker-image
              source:
                repository: appropriate/curl
            run:
              path: sh
              args:
              - -c
              - |
                 i=0
                 while [[ $i -ne 1 ]]; do
                   code=`curl -LI http://pcfdemoapp-staging.pcflab.jp -o /dev/null -w '%{http_code}\n' -s`;
                   if [[ ${code} = "200" ]]; then
                       echo ${code};
                     echo "ok";
                   else
                     echo "abort!!";
                     exit 1
                   fi
                   i=`expr $i + 1`;
                   sleep 1;
                 done

                 cat version-repo/java-bp.prop

                 ls -ltr app-repo
                 ls -ltr manifest-repo
                 cat manifest-repo/manifest-production.yml

                 cp app-repo/*.jar finaldir
                 app=`basename finaldir/*jar`
                 bp=`cat version-repo/*.prop`

                 str1="buildpack:"
                 str2='path:'

                 echo $'  '$str2$' '$app >> manifest-repo/manifest-production.yml
                 echo $'  '$str1$' '$bp >> manifest-repo/manifest-production.yml

                 cp manifest-repo/manifest-production.yml finaldir/manifest-production.yml

                 ls -ltr finaldir
                 cat finaldir/manifest-production.yml

      - put: cf-production
        params:
          manifest: finaldir/manifest-production.yml
          current_app_name: pcfdemoapp
  - name: roll-back
    plan:
      - get: app-repo
      - get: version-repo
      - task: roll-back
        config:
            platform: linux
            image_resource:
              type: docker-image
              source:
                repository: governmentpaas/cf-cli
            inputs:
              - name: app-repo
              - name: version-repo
            params: 
              api: {{cf-api}}
              user: {{cf-admin}}
              pass: {{cf-admin-pass}}
              org: {{cf-org}}
              space_prod: {{cf-space-prod}}
              space_stg: {{cf-space-staging}}
            run:
              path: sh
              args:
              - -c
              - |
                bp=`cat version-repo/*.prop`
                cf login -a $api -u $user -p $pass -o $org -s $space_prod --skip-ssl-validation
                cf delete-buildpack  $bp -f      
                cf buildpacks
                cf push pcfdemoapp -p app-repo/*jar -b java_buildpack_offline

                cf login -a $api -u $user -p $pass -o $org -s $space_stg --skip-ssl-validation
                cf push pcfdemoapp -p app-repo/*jar -b java_buildpack_offline



