repo: java-buildpack
cf-org: pcfdemoapp
cf-space-staging: staging
cf-space-prod: production
cf-username: kabu
cf-password: kabu
cf-admin: admin
cf-admin-pass:  j12ej8EuGTKzrDXQg3z1MSfH2un4-6_4
cf-api: api.system.kabdev.xyz
gcs-bucket-releases: pcfdemoapp-releases
appname: pcfdemoapp
domain: apps.kabdev.xyz
github-uri: https://github.com/tkaburagi1214/manifests.git
github-uri-bp: https://github.com/tkaburagi1214/buildpacks.git
github-branch: master
ver-bucket: java-buildpack-version